feat(frontier):add pagination to ListOrganizations
raystack/proton pull request #368
Opened 2024-08-14 05:59 UTC by AmanGIT07

Add new fields to `ListAllOrganizationsRequest` and `ListAllOrganizationsResponse` to enable pagination.

Fields added:
`page_size` ,`page_num` to `ListAllOrganizationsRequest` message
`total_pages` to `ListAllOrganizationsResponse` message

2024-08-20 05:38 UTC, anujk14 requested changes

2024-08-20 05:40 UTC, anujk14 commented on raystack/frontier/v1beta1/admin.proto
> +  int32 total_pages = 2[
Also, the term `total_pages` is dependant on the `page_size` that the customer has chosen. If we name it as `total_pages` we will need to keep changing it as per the `page_size` in request. `count` would be more standard and uniform, in my opinion.

2024-08-20 05:43 UTC, AmanGIT07 commented on raystack/frontier/v1beta1/admin.proto
> +  int32 total_pages = 2[
`count` gives us total items in the response. I will be `<= page_size` requested. `total_pages` gives us the total number of pages which frontend can use to populate page footers. Both are serving different purposes

2024-08-20 06:19 UTC, anujk14 commented on raystack/frontier/v1beta1/admin.proto
> +  int32 total_pages = 2[
I think number of pages is a fairly straightforward calculation. However, `total_pages` still does not give us the total count of objects, should we want to show that number somewhere.
The API should be fairly independent of the consumer(UI in this case).

2024-08-20 14:07 UTC, AmanGIT07 commented on raystack/frontier/v1beta1/admin.proto
> +  int32 total_pages = 2[
Updated the `ListAllOrganizationsResponse` message to give count as output

2024-08-22 11:00 UTC, anujk14 approved these changes

2024-08-22 11:01 UTC, merged